name: Build Platforms

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Build Android
        run: flutter build apk --release
      
      - name: Build Web
        run: flutter build web --release
      
      - name: Build Windows
        run: flutter build windows --release
      
      - name: Build Linux
        run: flutter build linux --release
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: builds
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/web
            build/windows/runner/Release
            build/linux/release
